version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: finance-postgres
    restart: always
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_password
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: finance-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finance_db
      SPRING_DATASOURCE_USERNAME: finance_user
      SPRING_DATASOURCE_PASSWORD: finance_password
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: finance-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend